SELECT PRODUCT_ID AS ID_PRODUCTO, PRODUCT_NAME AS NOM_PRODUCTO,
DESCRIPTION AS DESCRIPCION, GROUP_CODE AS ID_GRUPO, SUB_GROUP_CODE AS ID_SUBGRUPO,
Codigo_Marca AS ID_MARCA,CATEGORY AS CATEGORIA,UPPER (PRODUCT_TYPE) AS TIPO_PRODUCTO,
CODE_PROV_O_ALT AS EAN, 
`Custom Field 2` AS EAN_COLECTIVA,
`Custom Field 3` AS EAN_CORRUGADO,
OH AS EXISTENCIA, COMMITED AS ASIGNADO, 
AVAILABLE AS DISPONIBLE, UM,
VOLUMEN, LARGO, ANCHO, ALTURA, WEIGHT AS PESO,
AVERAGE_COST AS COSTO_PROMEDIO, Ultimo_Costo_Promedio,Costo_Ultima_Produccion, 
SELL AS PRECIO, TOTAL_INV_COST AS COSTO_INVENTARIO,
`GL COST CODE` AS ID_CUENTA_COSTOS, `GL INCOME CODE` AS ID_CUENTA_INGRESO, `GL INVEN CODE` AS ID_CUENTA_INVENTARIO,
On_Production AS EN_PRODUCCION, 
Fecha_Ultima_Produccion AS FECHA_ULTIMA_PRODUCCION,
CURRENT_DATE ( ) AS FECHA_DATOS
FROM INVT_Ficha_Principal 
WHERE TEMP_MODIFY = FALSE;